### PR TITLE
FIX new_kernel_exists in collect_kernel_info always returns true

### PR DESCRIPTION
**Pull request by pielas**
collect_kernel_info module reported kernel change(`new_kernel_exists` set to true) even in case when kernel did not change.

### CODE REVIEW

**Comment by lae** [comment]
Duplicate of #206? I was waiting for someone to review that and then forgot about it, actually...

**Comment by pielas** [comment]
Ah, it looks so. I only checked if it's fixed on develop :)

**Comment by lae** [comment]
Does that other PR look fine codewise and does it work for you, then? I think the `decode("utf-8")` isn't necessary because Ansible's `to_text()` method should take care of it, iirc.

**Comment by pielas** [comment]
@lae yes, I wanted explicit conversion to string, but indeed it seems that it isn't necessary and for my case adding parentheses is enough

**Comment by lae** [comment]
Ok thank you, I merged the other PR into develop, which I've actually been using for the past two months without issue (merged locally) now that I think about it.

**Pull request closed without merging**
