### PR TITLE
#57 changed when condition to use bool declaration for boolean variables

### PR DESCRIPTION
**Pull request by trickert76**
Please have a look. At the moment I didn't test that - because I don't have an idea how to integrate the git repo into my playbook instead of the ansible-galaxy role.

### CODE REVIEW

**Comment by lae** [comment]
Could you add spaces around the `|` operator (an amend commit is fine)? The existing codebase follows that style and I'd like to keep it consistent.

This is for your reference but you can install roles from github (or any other vcs source really) like below.

```bash
ansible-galaxy install $URL,$VERSION,$ROLENAME
# e.g.
ansible-galaxy install https://github.com/lae/ansible-node-exporter/archive/feature/download_url.tar.gz,download_url,lae.node-exporter --force
ansible-galaxy install https://github.com/lae/ansible-role-proxmox/archive/develop.tar.gz,v1.6.0-pre,lae.proxmox --force
```

You could also just symlink `~/.ansible/roles/lae.proxmox` to your checked out copy as well, since that's where Ansible looks for roles (and thus ansible-galaxy installs roles into by default). I actually use this method for development/local testing.

**Comment by trickert76** [comment]
Yeah, thanks - I learned about the requirements.yml

```
---
- src: geerlingguy.ntp
- src: systemli.letsencrypt
- src: https://github.com/trickert76/ansible-role-proxmox.git
  version: fix/remove_warning_bare_boolean_variables
  name: lae.proxmox
```
and calling 

`ansible-galaxy install -r requirements.yml --force`

**Comment by trickert76** [comment]
Just one question about the code style.
If it is
`when: var | bool`

should it be better
`when: "var | bool"`

**Comment by lae** [comment]
Actually, good point. It'd be best if they were quoted, too.

**Comment by trickert76** [comment]
Ok, I think, I'm ready.

**Pull request merged**
